In [5]:
import math
deg=15
print(math.pi * deg/180)

0.2617993877991494


In [4]:
radian=.52
print(180 * radian/math.pi)

29.79380534680281


In [1]:
height= 5
base1=int(input("give the first base"))
base2=int(input("give the second base"))
area = height*(base1+base2)/2
print(area)

27.5


In [2]:
base=int(input("give the base"))
height=int(input("give the height"))
area = height*base
print(area)

30


In [6]:
radius=int(input("give the radius"))
height=int(input("give the height"))
volume= math.pi * radius**2 *height
surface= 2 * math.pi * radius ** 2 +2*math.pi*radius *height
print("the surface is :",surface)
print("the volume is :",volume)


the surface is : 376.99111843077515
the volume is : 452.3893421169302


In [8]:
radius=float(input("give the radius"))
volume= 4/3 * math.pi * radius**3
surface= 4 * math.pi * radius ** 2 
print("the surface is :",surface)
print("the volume is :",volume)


the surface is : 7.0685834705770345
the volume is : 1.7671458676442584


In [12]:
diameter=float(input("give the diameter"))
angle=float(input("give the angle"))
length = math.pi * angle/180 * (diameter/2)
print(length)

3.141592653589793


In [13]:
radius=float(input("give the radius"))
angle=float(input("give the angle"))
sector = math.pi * angle/360 * radius
print(length)

3.141592653589793


In [17]:
x = float(input("give a coefficient"))
y = float(input("give a coefficient"))
z = float(input("give a coefficient"))
print( -y**2 - 4*x*z)

64.0


In [23]:
n= int(input("give the size n"))
factors=[]
smallest=1
for ind in range(n,1, -1):
    if smallest%ind!=0 :
        factors.append(ind)
        smallest*=ind
print("the factors:", factors)
print("the result:", smallest) 

the factors: [13, 12, 11, 10, 9, 7]
the result: 1081080


In [31]:
n= int(input("give the size n"))
sum_squre=sum(j for j in range(1,n+1))**2
square_sum= sum(j**2 for j in range(1, n+1))
print(sum_squre-square_sum)

5434


In [32]:
base= int(input("give the base"))
power= int(input("give the power"))
print ( sum(int(j) for j in str(base**power)))

115


In [36]:
n= int(input("give the size n"))
sum_dividors=0
for ind in range(n,1, -1):
    if n%ind==0 :
        sum_dividors+=ind
print(sum_dividors>n)

False


In [53]:
n= int(input("give the size n"))
amicables=set()
for i in range(2,n+1):
    if i in amicables:
        continue
    test=sum(j for j in range (1,i) if i%j==0)
    test2=sum (j for j in range (1,test) if test%j==0)
    if i==test2 and i!=test:
        amicables.add(i)
        amicables.add(test2)
print(sum(amicables))

0


In [58]:
n= int(input("give the size n"))
divisors_sum=0
for j in range(1,(n//2)+1):
    if n%j==0:
        divisors_sum+=j
print(divisors_sum)

16


In [59]:
def permute_string(str):
    if len(str) == 0:
        return ['']
    prev_list = permute_string(str[1:len(str)])
    next_list = []
    for i in range(0,len(prev_list)):
        for j in range(0,len(str)):
            new_str = prev_list[i][0:j]+str[0]+prev_list[i][j:len(str)-1]
            if new_str not in next_list:
                next_list.append(new_str)
    return next_list

print(permute_string('ABCD'))

['ABCD', 'BACD', 'BCAD', 'BCDA', 'ACBD', 'CABD', 'CBAD', 'CBDA', 'ACDB', 'CADB', 'CDAB', 'CDBA', 'ABDC', 'BADC', 'BDAC', 'BDCA', 'ADBC', 'DABC', 'DBAC', 'DBCA', 'ADCB', 'DACB', 'DCAB', 'DCBA']


In [65]:
lucky_size= int(input("give the size of the lucky list"))
lucky_list=list(range(-1,lucky_size*lucky_size+9,2))
i=2
while lucky_list[i:]:lucky_list=sorted(set(lucky_list)-set(lucky_list[lucky_list[i]::lucky_list[i]]));i+=1
print(lucky_list[1:lucky_size+1])

[1, 3, 7, 9, 13, 15, 21, 25, 31, 33]


In [67]:
first= int(input("give the size n"))
second= int(input("give the size n"))
product=0
for j in range(second):
    product+=first
print(product)

20


In [28]:
import math
n=int(input("give the limit of the Sieve of Eratosthenes"))
large_list=[True for j in range(n+1)]
for i in range(2, math.ceil((math.sqrt(n)))):
    if large_list[i]==True:
        for j in [i**2 +k*i for k in range(n) if i**2 +k*i<= n]:
            large_list[j]=False
print ( [j for j in range(2,n+1) if large_list[j]==True])

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]


In [18]:
def ispalindrome(to_be_tested):
    converted=str(to_be_tested)
    if( converted==converted[::-1]):
        return True
    return False

i=int(input("give the lower bound"))
while ispalindrome(i)==False:
    i+=1

print(i)



101


In [21]:
i=int(input("give the upper bound"))
while ispalindrome(i)==False:
    i-=1

print(i)

11


In [3]:
from fractions import Fraction
value_to_calculate=float(input("give the value to evaluate"))
print(Fraction(value_to_calculate).limit_denominator())

27/5


In [17]:
from functools import reduce
n=int(input("give the limit of the catalan series"))
result= reduce((lambda x, y: x * y), [(n+k)/k for k in range(2,n+1)])
print(result)

428.99999999999994


In [21]:

n=int(input("give the limit of the catalan series"))

f'{n:,}'

'55,555'

In [ ]:
from math import sqrt
distance=sqrt((x1[0]-x2[0])**2+y1[0]-y2[0])**2)
print(distance)

In [25]:
from math import tan,pi
number_of_sides=int(input("give the number of sides"))
size_of_side=int(input("give the size of a side"))
apothem= size_of_side/(2*tan(pi/number_of_sides))
area=number_of_sides*size_of_side*apothem/2
print(area)

25.000000000000004


In [28]:
V=int(input('give speed'))
T=int(input('give temp'))
chill_index=13.12 + 0.6215*T - 11.37* (V**0.16) + 0.3965*T *(V**0.16)
print(chill_index)

31.429969064035422


In [30]:
from math import sqrt

a=int(input("give coef"))
b=int(input("give coef"))
c=int(input("give coef"))

disc= b**2 -4*a*c
first_solution= (-b+sqrt(disc))/(2*a)
second_solution= (-b-sqrt(disc))/(2*a)
print(first_solution, second_solution)

-0.8345788509735982 -1.7254211490264018


In [33]:
c=int(input("give binary number"),2)
print(c)

43


In [34]:
Y = (-5.79829066331+4.55640490659j)
print("the real part is", Y.real)
print("the imaginary part is", Y.imag)


the real part is -5.79829066331
the imaginary part is 4.55640490659


In [36]:
Y = (-5.79829066331+4.55640490659j)
Z = (5.79829066331-4.55640490659j)
print(Y+Z)
print(Y-Z)
print(Y*Z)
print(Y/Z)

0j
(-11.59658132662+9.11280981318j)
(-12.8593489434305+52.838720056281346j)
(-1+0j)


In [37]:
from math import sqrt, atan
Y = (-5.79829066331+4.55640490659j)
number_length= sqrt(Y.real**2+Y.imag**2)
number_angle= atan(Y.imag/Y.real)
print(number_length, number_angle)

7.374347448352657 -0.6660337584770641


In [45]:
import cmath
cn1 = cmath.rect(2, cmath.pi)
print(cn1)

(-2+2.4492935982947064e-16j)


In [49]:
from decimal import *
list_to_find=list(map(Decimal,input("give the list").split(",")))
print("the min is", min(list_to_find))
print("the max is", max(list_to_find))


the min is 1
the max is 6


In [54]:
from decimal import *
list_to_find=list(map(Decimal,input("give the list").split(",")))
print(sum(list_to_find))
list_to_find.sort(reverse=True)
print(list_to_find)

20.33
[Decimal('7.25'), Decimal('3.45'), Decimal('2.69'), Decimal('2.45'), Decimal('2.45'), Decimal('2.00'), Decimal('0.04')]


In [56]:
from math import sqrt,e
value=int(input("give the integer to calculate"))
print(sqrt(value))
print(e**value)

2.0
54.59815003314423


In [60]:
import decimal
context = decimal.getcontext()
# for key in context.keys():
    # print(key)
print(context)

Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999, Emax=999999, capitals=1, clamp=0, flags=[], traps=[InvalidOperation, DivisionByZero, Overflow])


In [65]:
sample=float(input("give the sample value"))
print("the orignal number is", sample)

for j in range(1,5):
    
    decimal.getcontext().prec=j
    print("the numbuer at precision ", j, " is ",value*1, sep='')

the orignal number is 0.26598
the numbuer at precision 1 is 0.3
the numbuer at precision 2 is 0.27
the numbuer at precision 3 is 0.266
the numbuer at precision 4 is 0.2660


In [78]:
sample=0.24555
decimal.getcontext().prec=2
decimal.getcontext().rounding=  ROUND_UP
print("the value up is", sample*1)
decimal.getcontext().rounding=ROUND_DOWN
print("the value down is", sample*1)


the value up is 0.24555
the value down is 0.24555


In [82]:
with decimal.localcontext() as context:
    context.prec = 2
    print('Local precision:', context.prec)
    print('22/7 =', (decimal.Decimal('22') / 7))
print()
print('Default precision:', decimal.getcontext().prec)
print('22 /7 =', (decimal.Decimal('22') / 7))

Local precision: 2
22/7 = 3.1

Default precision: 28
22 /7 = 3.142857142857142857142857143


In [89]:
value_to_calculate=Decimal('0.7')
print(Fraction(value_to_calculate).limit_denominator())

7/10


In [90]:
f1=Fraction(2,3)
f2=Fraction(5,7)
print(f1+f2)

29/21


In [94]:
value_to_calculate=pi
print(Fraction(value_to_calculate).limit_denominator(6))


19/6


In [104]:
import random
random.choice(range(0, 101, 2))

40

In [123]:
random.choice("achraf")

'a'

In [129]:
initital_list=[1,3,5,7,9,11]
print(random.shuffle(initital_list))
print(initital_list)

None
[3, 5, 9, 1, 7, 11]


In [130]:
results = {
    'heads': 0,
    'tails': 0,
}
sides = list(results.keys())

for i in range(10000):
    results[random.choice(sides)] += 1

print('Heads:', results['heads'])
print('Tails:', results['tails'])

Heads: 5010
Tails: 4990


In [142]:
random.choice(["red","green", 'blue'])

'green'

In [145]:
abs(-5.432)

5.432

In [148]:
import statistics
statistics.stdev([4, 2, 5, 8, 6] )

2.23606797749979

In [4]:
mantissa = float(input("give the mantissa"))
exponent = int(input("give the exponent"))
print(mantissa*2**exponent)

4.0


In [7]:
from math import sqrt
edge=float(input("please give the edge"))
volume=  edge**3/(6*sqrt(2))
print(volume)

117.85113019775791


In [2]:
from math import factorial

precision=float(input("please give the precision wanted"))
value1=0
k=0
value2=1
while abs(value1-value2)>precision:
    k+=1
    value1=value2
    value2+=1/factorial(k)

print(value2)

2.7182818284467594


In [7]:
from math import sin, cos, radians

for n in range(1, 10):
	circle_1 = 50 * (1 + sin(radians(n*10)))
	circle_2 = 50 * (1 + cos(radians(n*10)))
	print("#".center(int(circle_1)))
	print("*".center(int(circle_2)))


                            #                             
                                                 *                                                 
                                 #                                 
                                               *                                                
                                     #                                     
                                              *                                              
                                        #                                         
                                           *                                            
                                           #                                            
                                        *                                         
                                              #                                              
                                     *                              

In [9]:
for i in range(10):
    print(' '*int(10*cos(radians(i))+10) + '.')

                    .
                   .
                   .
                   .
                   .
                   .
                   .
                   .
                   .
                   .


In [22]:
from math import sqrt
side_to_calculate=set("x")
sides=set(["a","b","c"])
while len(side_to_calculate.intersection(sides))==0:
    side_to_calculate=set(input("which side do you want to calculate?"))
values=[]
for j in list(sides.difference(side_to_calculate)):
    values.append(int(input("length of side")))
if list(side_to_calculate)[0]=="c":
    print("the value of c is", sqrt(values[0]**2+values[1]**2))
else :
    print("the missing side is: ", sqrt(values[1]**2-values[0]**2))

the missing side is:  3.0


In [23]:
from math import  ceil
original_number= float(input("give the starting number"))
for prec in range(4):
    print( ceil(original_number*10**prec)/10**prec)

124.0
123.1
123.02
123.013


In [26]:
from numpy import arange
print(arange(0, 1, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [55]:
import numpy as np
n=5
i,j=0,0
current_max=n-1
current_min=0
A=np.zeros((n,n))
for k in range(1,n**2+1):
    A[i][j]=k
    if i==current_max and j<current_max :
        j+=1
    elif j==current_min and i<current_max:
        i+=1
    elif (i==current_min and j>current_min):
        j-=1
    elif (j==current_max or i>current_min):
        i-=1
    if (j==current_min+1 and i==current_min):
        current_min+=1
        current_max-=1
print(np.matrix.transpose(A))


[[ 1.  2.  3.  4.  5.]
 [16. 17. 18. 19.  6.]
 [15. 24. 25. 20.  7.]
 [14. 23. 22. 21.  8.]
 [13. 12. 11. 10.  9.]]


In [61]:
import random as rnd
import datetime

start_date = datetime.date(2021, 1, 1)
end_date = datetime.date(2021, 12, 31)
difference=( end_date- start_date).days
random_number=rnd.choice(range(difference))
print(start_date+ datetime.timedelta(days=random_number))


2021-09-09


In [64]:
a=int(input("give the first value"))
b=int(input("give the second value"))

while b!=0:
    c=b
    b=a%b
    a=c
print("the gcd is ", a) 

the gcd is  2


In [1]:
from skimage.color import rgb2hsv

rgb2hsv((0, 0.0, 100.0))

ModuleNotFoundError: No module named 'skimage'

In [6]:
from math import sqrt
up_limit=int(input("please give the upper bound"))
down_limit=int(input("please give the lower bound"))
result_list=[]

for i in range(down_limit, up_limit):
    if sqrt(i).is_integer():
        result_list.append(i)

print(result_list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [10]:
value=1
print(hex(value))

0x1


In [15]:
import random as rnd
for j in range(10):
    print(rnd.randint(1,100))

81
91
40
71
56
61
78
41
31
98


In [21]:

n=input("give the number")
if n.isnumeric():
    n=int(n)
    S=sum([j for j in range(1,n) if n%j==0])
    print(S)
else:
    print("please select an integer")

16


In [23]:
n=int(input("give the number"))
print(n*(n+1)*(n+2)/6)

10.0


In [26]:
start=int(input("give the number"))
end =int(input("give the number"))
power=int(input("give the number"))
S=sum([j**power for j in range(start, end+1)])
print(S)

618507


In [30]:
def hamming_distance(x, y):
  return bin(x ^ y).count('1')
x = 2 
y = 3
print("Hamming distance between",x,"and",y,"is",hamming_distance(x, y))
x = 43 
y = 87
print("Hamming distance between",x,"and",y,"is",hamming_distance(x, y))

Hamming distance between 2 and 3 is 1
Hamming distance between 43 and 87 is 5


In [32]:
number= int(input("give the number"))
x= int(input("give the number"))
y= int(input("give the number"))
smaller=min(x,y)
bigger=max(x,y)
if number<smaller:
    number=smaller
if number>bigger:
    number=bigger
print(number)

5


In [35]:
number= int(input("give the number"))
tmp=0
for index,letter in enumerate(str(number)):
    tmp+=int(letter)**(index+1)
print(tmp==number)  

True
